### ISSUE TITLE
Error when used with VisualEditor extension

### ISSUE THREAD

**Issue by pawitp** [bovender/PubmedParser#4]
**Setup**
MediaWiki 1.32.1
PHP 7.3.5
MariaDB 10.1.38
VisualEditor 0.1.0 (e82e120)
PubmedParser 4.0.3

LocalSettings.php
```
$wgShowExceptionDetails = true;
wfLoadExtension( 'PubmedParser' );
wfLoadExtension( 'VisualEditor' );
$wgDefaultUserOptions['visualeditor-enable'] = 1;
```

**Issue**
Open Developer Console and the follow Stack Trace is shown.
```
[60ccb3d4c9c6c2cbb8eed627] /wiki/load.php?debug=false&lang=en&modules=startup&only=scripts&skin=vector   BadMethodCallException from line 848 of /var/www/html/wiki/includes/session/SessionManager.php: Sessions are disabled for this entry point
Backtrace:
#0 /var/www/html/wiki/includes/session/SessionManager.php(310): MediaWiki\Session\SessionManager->getSessionFromInfo(MediaWiki\Session\SessionInfo, WebRequest)
#1 /var/www/html/wiki/includes/session/SessionManager.php(244): MediaWiki\Session\SessionManager->getEmptySessionInternal(WebRequest)
#2 /var/www/html/wiki/includes/session/SessionManager.php(194): MediaWiki\Session\SessionManager->getEmptySession(WebRequest)
#3 /var/www/html/wiki/includes/WebRequest.php(750): MediaWiki\Session\SessionManager->getSessionForRequest(WebRequest)
#4 /var/www/html/wiki/includes/user/User.php(1377): WebRequest->getSession()
#5 /var/www/html/wiki/includes/user/User.php(447): User->loadFromSession()
#6 /var/www/html/wiki/includes/user/User.php(5487): User->load()
#7 /var/www/html/wiki/includes/user/User.php(3174): User->loadOptions()
#8 /var/www/html/wiki/includes/context/RequestContext.php(336): User->getOption(string)
#9 /var/www/html/wiki/includes/Message.php(381): RequestContext->getLanguage()
#10 /var/www/html/wiki/includes/Message.php(1299): Message->getLanguage()
#11 /var/www/html/wiki/includes/Message.php(851): Message->fetchMessage()
#12 /var/www/html/wiki/includes/Message.php(943): Message->toString(string)
#13 /var/www/html/wiki/extensions/PubmedParser/includes/PubmedParser_Extension.php(84): Message->text()
#14 /var/www/html/wiki/extensions/PubmedParser/includes/PubmedParser_Extension.php(50): PubmedParser\Extension::loadMessages()
#15 /var/www/html/wiki/includes/Hooks.php(174): PubmedParser\Extension::setup(Parser)
#16 /var/www/html/wiki/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#17 /var/www/html/wiki/includes/parser/Parser.php(369): Hooks::run(string, array)
#18 /var/www/html/wiki/includes/StubObject.php(112): Parser->firstCallInit()
#19 /var/www/html/wiki/includes/StubObject.php(138): StubObject->_call(string, array)
#20 /var/www/html/wiki/includes/cache/MessageCache.php(1190): StubObject->__call(string, array)
#21 /var/www/html/wiki/includes/cache/MessageCache.php(1166): MessageCache->getParser()
#22 /var/www/html/wiki/includes/Message.php(1282): MessageCache->transform(string, boolean, LanguageEn, NULL)
#23 /var/www/html/wiki/includes/Message.php(883): Message->transformText(string)
#24 /var/www/html/wiki/includes/Message.php(943): Message->toString(string)
#25 /var/www/html/wiki/includes/EditPage.php(3614): Message->text()
#26 /var/www/html/wiki/extensions/VisualEditor/includes/VisualEditorDataModule.php(70): EditPage::getCopyrightWarning(Title, string, string)
#27 /var/www/html/wiki/extensions/VisualEditor/includes/VisualEditorDataModule.php(25): VisualEditorDataModule->getMessageInfo(ResourceLoaderContext)
#28 /var/www/html/wiki/includes/resourceloader/ResourceLoaderModule.php(708): VisualEditorDataModule->getScript(ResourceLoaderContext)
#29 /var/www/html/wiki/includes/resourceloader/ResourceLoaderModule.php(675): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#30 /var/www/html/wiki/includes/resourceloader/ResourceLoaderModule.php(812): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#31 /var/www/html/wiki/includes/resourceloader/ResourceLoaderStartUpModule.php(257): ResourceLoaderModule->getVersionHash(ResourceLoaderContext)
#32 /var/www/html/wiki/includes/resourceloader/ResourceLoaderStartUpModule.php(435): ResourceLoaderStartUpModule->getModuleRegistrations(ResourceLoaderContext)
#33 /var/www/html/wiki/includes/resourceloader/ResourceLoaderModule.php(708): ResourceLoaderStartUpModule->getScript(ResourceLoaderContext)
#34 /var/www/html/wiki/includes/resourceloader/ResourceLoaderModule.php(675): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#35 /var/www/html/wiki/includes/resourceloader/ResourceLoaderModule.php(812): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#36 /var/www/html/wiki/includes/resourceloader/ResourceLoader.php(660): ResourceLoaderModule->getVersionHash(ResourceLoaderContext)
#37 [internal function]: ResourceLoader->{closure}(string)
#38 /var/www/html/wiki/includes/resourceloader/ResourceLoader.php(672): array_map(Closure, array)
#39 /var/www/html/wiki/includes/resourceloader/ResourceLoader.php(753): ResourceLoader->getCombinedVersion(ResourceLoaderContext, array)
#40 /var/www/html/wiki/load.php(51): ResourceLoader->respond(ResourceLoaderContext)
#41 {main}
```

**Suspect**
When requesting the JS resource file, PubmedExtension is loading messages which are language-dependent. However, language-dependent data is not allowed in JS files due to caching, thus MediaWiki erroring out.

I've applied a temporary fix to my setup by guarding the load messages method, but I'm not sure if it's the proper fix or not.

```
if ( !defined( 'MW_NO_SESSION' ) ) self::loadMessages();
```

**Comment by bovender** [comment]
Thanks for reporting as well as researching this. It seems to me this should be an extension-independent problem? Will have to find out if PubmedParser still uses the canonical method to load the messages...

**Comment by bovender** [comment]
Currently the messages are being loaded and cached in static class variables upon initialization. I suspect I must defer message loading. However, I am unable to test this myself as I don't have a Wiki with the VisualEditor at hand (a recent attempt to use it failed, but that is a different story).

Would it be possible for you to try and move the line

    self::loadMessages();

from the `setup` function in `PubmedParser_Extension.php` to the top of the `render` function?

**Comment by pawitp** [comment]
Moving the load from `setup` to `render` fixes the issue.

By the way, for testing, you don't need the full setup with `parsoid`. Just turning on the extension is sufficient to trigger to issue.
