### ISSUE TITLE
1.34 breaking change - removal of DB_SLAVE, replaced by DB_REPLICA

### ISSUE THREAD

**Issue by greenaussie** [bovender/PubmedParser#5]
1.34 breaking change - removal of DB_SLAVE, replaced by DB_REPLICA,  see core RELEASE-NOTES-1.34, "The constant DB_SLAVE, deprecated in 1.28, has been removed. Use DB_REPLICA".

There is a reference to DB_SLAVE on line 231 of `includes/PubmedParser_Core.php`

The impact of the removal was an error was thrown for existing PMID references (see below) until there is a reload of the PMID cache forced by using resaving the page with `{{PMIDxxxxx|reload}}` (not a good solution if you have many thousands of references).

After making the suggested change, Redis and any front end caching to be refreshed (I use varnish).

e.g.:

```text
[adf27393acac50080f257713] /embryology/index.php/Abnormal_Development_-_Environmental UnexpectedValueException from line 462 of /var/www/html/embryology/includes/libs/rdbms/loadbalancer/LoadBalancer.php: Invalid server index index #DB_SLAVE

Backtrace:

#0 /var/www/html/embryology/includes/libs/rdbms/loadbalancer/LoadBalancer.php(896): Wikimedia\Rdbms\LoadBalancer->getConnectionIndex(string, array, string)
#1 /var/www/html/embryology/includes/libs/rdbms/loadbalancer/LoadBalancer.php(1043): Wikimedia\Rdbms\LoadBalancer->getConnection(string, array, string, integer)
#2 /var/www/html/embryology/includes/GlobalFunctions.php(2576): Wikimedia\Rdbms\LoadBalancer->getMaintenanceConnectionRef(string, array, string)
#3 /var/www/html/embryology/extensions/PubmedParser/includes/PubmedParser_Core.php(231): wfGetDB(string)
#4 /var/www/html/embryology/extensions/PubmedParser/includes/PubmedParser_Core.php(207): PubmedParser\Core->getReadDb()
#5 /var/www/html/embryology/extensions/PubmedParser/includes/PubmedParser_Core.php(153): PubmedParser\Core->fetchFromDb(string)
#6 /var/www/html/embryology/extensions/PubmedParser/includes/PubmedParser_Core.php(60): PubmedParser\Core->lookUp()
#7 /var/www/html/embryology/extensions/PubmedParser/includes/PubmedParser_Extension.php(77): PubmedParser\Core->__construct(string, string, string)
#8 /var/www/html/embryology/includes/parser/Parser.php(3816): PubmedParser\Extension::render(Parser, string, string)
#9 /var/www/html/embryology/includes/parser/Parser.php(3519): Parser->callParserFunction(PPFrame_Hash, string, array)
#10 /var/www/html/embryology/includes/parser/PPFrame_Hash.php(254): Parser->braceSubstitution(array, PPFrame_Hash)
#11 /var/www/html/embryology/includes/parser/Parser.php(3330): PPFrame_Hash->expand(PPNode_Hash_Tree, integer)
#12 /var/www/html/embryology/includes/parser/Parser.php(1489): Parser->replaceVariables(string)
#13 /var/www/html/embryology/includes/parser/Parser.php(593): Parser->internalParse(string)
#14 /var/www/html/embryology/includes/content/WikitextContent.php(368): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#15 /var/www/html/embryology/includes/content/AbstractContent.php(555): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#16 /var/www/html/embryology/includes/Revision/RenderedRevision.php(267): AbstractContent->getParserOutput(Title, integer, ParserOptions, boolean)
#17 /var/www/html/embryology/includes/Revision/RenderedRevision.php(236): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(WikitextContent, boolean)
#18 /var/www/html/embryology/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string)
#19 /var/www/html/embryology/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
#20 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#21 /var/www/html/embryology/includes/Revision/RenderedRevision.php(198): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#22 /var/www/html/embryology/includes/poolcounter/PoolWorkArticleView.php(196): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#23 /var/www/html/embryology/includes/poolcounter/PoolCounterWork.php(125): PoolWorkArticleView->doWork()
#24 /var/www/html/embryology/includes/page/Article.php(791): PoolCounterWork->execute()
#25 /var/www/html/embryology/includes/actions/ViewAction.php(63): Article->view()
#26 /var/www/html/embryology/includes/MediaWiki.php(511): ViewAction->show()
#27 /var/www/html/embryology/includes/MediaWiki.php(302): MediaWiki->performAction(Article, Title)
#28 /var/www/html/embryology/includes/MediaWiki.php(900): MediaWiki->performRequest()
#29 /var/www/html/embryology/includes/MediaWiki.php(527): MediaWiki->main()
#30 /var/www/html/embryology/index.php(44): MediaWiki->run()
#31 {main}
```

**Comment by bovender** [comment]
Thanks for the heads-up, fixed by e431dfd.

Version 5.0.0 released just now.
